In [21]:
# imports

import os
import numpy as np
from tinygrad import Tensor

# setting tinygrad device to gpu since METAL is broken on older macs
os.environ['GPU'] = '1'

In [2]:
# perceptron

class Perceptron:
    def __init__(self, input_size):
        # init inputs, weights and bias
        self.inputs = Tensor.randint(1, input_size)
        self.weights = Tensor.randn(1, input_size)
        self.bias = Tensor.randn(1,1)

    def forward(self):
        
        # perform forward perceptron computation

        # take sum of dot prod. of inputs (transposed) and their resp. weight
        # we take sum because we do an element wise op
        output = (self.inputs.T).dot(self.weights).sum()

        # add bias
        output = output.add(self.bias)
        
        # apply non-linear activation func.
        output = output.sigmoid()
        return output

# Spawn perceptron with input size 4
p1 = Perceptron(4)

# Forward pass
output = p1.forward()

print(p1.inputs.numpy())
print(output.numpy())

# see how we 'squash' the 4 input nodes to 1 output?

[[4 6 6 4]]
[[1.322044e-15]]


In [6]:
# Multi Output Perceptron

class MOP:
    def __init__(self, num_inputs, num_outputs):
        # init inputs, weights and bias
        self.inputs = Tensor.randint(1, num_inputs, low=-10, high=10)
        
        # each node now has multiple outputs, so we need to init multiple weights per output
        self.weights = Tensor.randn(num_inputs, num_outputs)
        self.bias = Tensor.randn(1,1)

    def forward(self):
        # perform forward MLP computation
        # we now need a matmul since in general, we cannot dot with matrices

        # matmul of input and their resp. weight
        # since we do a complex op matmul, we do not need to use sum, innate
        # we also do not need to transpose with matmul
        # otherwise we could do the same as the perceptron class, and do the transposed dot and sum

        output = (self.inputs).matmul(self.weights)

        # add bias
        output = output.add(self.bias)
        
        # apply non-linear activation func.
        output = output.sigmoid()
        return output

# Dense layer
# ( all inputs are densely connected to all outputs )
# ( so now we take out inputs, and 'squash' them into <1 outputs )


# Spawn dense layer with 3 inputs and 2 outputs
p1 = MOP(8,4)


# forward pass
output = p1.forward()

print(p1.inputs.numpy())
print(output.numpy())

# see how we 'squash' the 3 input nodes to 2 output nodes?

[[ -8   3  -3  -3  -6  -5   2 -10]]
[[9.9993065e-16 8.8749919e-03 3.4108248e-02 3.3258490e-07]]


In [15]:
# single layer neural network
# 3 -> 4 -> 2
# num of nodes

# input
input_layer = MOP(3,4)
print(input_layer.inputs.numpy())

# hidden layer
hidden_layer = MOP(input_layer.forward().size(dim=1), 2)
hidden_layer.inputs = input_layer.forward()
print(hidden_layer.inputs.numpy())

# output
output_layer = hidden_layer.forward()
print(output_layer.numpy())

# see how we went from 3 input nodes to 4 hidden layer nodes to 2 output nodes?

[[4 4 9]]
[[6.5402872e-07 8.8858127e-07 9.9999714e-01 4.3373516e-01]]
[[0.90946215 0.8645813 ]]
